In [1]:
import numpy 
numpy.__version__

'1.26.4'

In [2]:
import numpy as np
# Display Numpy built-in Documentation
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Ian\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\ian\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x =

## Fixed-Type Array in Python

Python offers several differnt options for storing data in efficient, fixed type data buffers. The built in array module(availabble in python 3.3) can be used can be used to create dense arrays of a uniform type.

In [52]:
import array
L = list(range(10))
A = array.array("i", L) # Here i is a type code indicating that the contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Much more useful is the **ndarray** object of the NumPy Package. While Python's array object provides efficient storage of array-based data, NumPy adds to this efficient operations to that data.

In [4]:
# Importing numpy
import numpy as np

# Creating arrays from Python's list
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Unlike Pyhon's lists, NumPy is constrained to arrays that all contain the same type. If types is not the same, NumPy will upcast if possible.

In [5]:
np.array([3.14, 4, 6, 8]) # Here integers are upcast to floating points.

array([3.14, 4.  , 6.  , 8.  ])

If I explicity want to set the data type of the resulting array, I can use the **dtype** keyword.

In [6]:
np.array([1, 2, 3, 4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

Finally unlike Python's list NumPy arrays can explicity be multidimensional.

In [7]:
# Initializing a multidimensional array
# nested list results in multidimensional array
np.array([range(i, i+3) for i in [2, 4, 6]])  # Inner list is treated as the rows of the resulting 2 dimensional array.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch.

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.

**Examples**

In [8]:
# Creating a length-10 array filled with zeros
np.zeros(10, dtype="int")


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Craeting a 3 by 5 array filled with ones That are floats
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Craeting a 3 by 5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# Creating a 3 by 5 filled with 2
np.full((3, 5), 2) 

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [12]:
# Creating an array filled with linear sequence
# Starting at 0 ending at 20 , step = 2
# This is similar to the built in range function
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Creating an array evenly spaced beween 0 and 1 containing 5 values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Craeting a 3 by 3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.64660812, 0.12648511, 0.78307571],
       [0.14803251, 0.1705058 , 0.53212717],
       [0.04636199, 0.97707052, 0.17047089]])

In [15]:
# Craete a 3 by 3 array of normally distributed random values with mean 0 and std 1
np.random.normal(0, 1, (3, 3))


array([[-1.30621698,  0.4470806 ,  0.67552619],
       [-0.84046681,  1.45027975,  0.61121152],
       [-0.6999306 ,  0.79851688,  2.45326598]])

In [16]:
# Craete a 3 by 3 array of random integers of values in the interval (0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 9, 0],
       [2, 4, 7],
       [6, 0, 3]])

In [17]:
# Craete a 3 by 3 identity matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

In [19]:
## See NumP's Documentation

## The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation:
even newer tools like Pandas (Chapter 3) are built around the NumPy array. This section will present several examples using NumPy array manipulation to access data
and subarrays, and to split, reshape, and join the arrays. While the types of operations
shown here may seem a bit dry and pedantic, they comprise the building blocks of
many other examples used throughout the book. Get to know them well!
We’ll cover a few categories of basic array manipulations here:

**Attributes of arrays**
Determining the size, shape, memory consumption, and data types of arrays

**Indexing of arrays**
Getting and setting the value of individual array elements

**Slicing of arrays**
Getting and setting smaller subarrays within a larger array

**Reshaping of arrays**
Changing the shape of a given array

**Joining and splitting of arrays**
Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let’s discuss some useful array attributes. We’ll start by defining three random
arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use
NumPy’s random number generator, which we will seed with a set value in order to
ensure that the same random arrays are generated each time this code is run.

In [20]:
import numpy as np
np.random.seed(123) # Seed for reproducibility

x1 = np.random.randint(10, size=6) # One dimensional array
x2  = np.random.randint(10, size=(3, 4)) # Two dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three dimensional array
x1
                       

array([2, 2, 6, 1, 3, 9])

In [21]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

Each array has attributes **ndim** (the number of dimensions), **shape** (the size of each
dimension), and **size** (the total size of the array):

In [23]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [25]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2.size:", x2.size)

x2 ndim: 2
x2 shape: (3, 4)
x2.size: 12


Another useful attribute is the dtype which gives me the type of the array.

In [27]:
# Get the type of array x3
print("type x3:", x3.dtype)

type x3: int32


Other attributes include **itemsize**, which lists the size **(in bytes)** of each array element, and **nbytes**, which lists the total size **(in bytes)** of the array.

In [29]:
print("item size:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

item size: 4 bytes
nbytes: 240 bytes


In general we expect nbytes to be itemsize multiplied by the number of items.

## Array Indexing Accesing single Elements

If you are familiar with Python’s standard list indexing, indexing in NumPy will feel
quite familiar. In a one-dimensional array, you can access the ith value (counting from
zero) by specifying the desired index in square brackets, just as with Python lists:

In [31]:
x1

array([2, 2, 6, 1, 3, 9])

In [32]:
# Getting the first item
x1[0]

2

In [33]:
# Getting the 4TH item
x1[3]

1

To index from the end use negative indices.

In [34]:
# Getting the last item
x1[-1]

9

In [35]:
# Third last item
x1[-3]

1

In Multidimensional array I access items using a comma seperated tuple of indices.

In [36]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [37]:
# acessing row 0 column 0
x2[0, 0]

6

In [39]:
# row 2 column 3
x2[(1, 2)]

0

In [41]:
# row 2 last item
x2[(1, -1)]

9

I can also modify valus using any of the index notation above.

In [43]:
x2[(1, -1)] = 5
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 5],
       [3, 4, 0, 0]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means,
for example, that if you attempt to insert a floating-point value to an integer array, the
value will be silently truncated. Don’t be caught unaware by this behavior!

In [46]:
x2[(1, -1)] = 5.2 # This will be truncated
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 5],
       [3, 4, 0, 0]])

## Array Slicing: Accessing Subarrays.

Just as we can use square brackets to access individual array elements, we can also use
them to access subarrays with the slice notation, marked by the colon (:) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of
an array x, use this:

**x[start:stop:step]**

If any of these are unspecified, they default to the values **start=0**, **stop=size of
dimension**, **step=1**. We’ll take a look at accessing subarrays in one dimension and in
multiple dimensions.

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x[:5] # Getting the first 5 elements

array([0, 1, 2, 3, 4])

In [55]:
x[4:7] # from the 4th to the 6th element

array([4, 5, 6])

In [58]:
# Number of dimension
x.size

10

In [59]:
x[::2] # start=0, stop=size of dimension(10), step=2

array([0, 2, 4, 6, 8])

In [61]:
x[1::2] # start=1, stop=size of dimension(10), step=2)

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array:

In [64]:
x[::-1] # all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [67]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

## Multidimensionals Subarrays

Multidimensional slices work in the same way, with multiple slices seperated by commas. For example:

In [74]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 5],
       [3, 4, 0, 0]])

In [75]:
x2[:2, :3] # two rows, 3 columns

array([[6, 1, 0],
       [9, 0, 0]])

In [78]:
x2[:3, ::2] # 3 rows and every other columns , steps=2

array([[6, 0],
       [9, 0],
       [3, 0]])

Finally, subarray dimensions can even be reversed together:

In [79]:
x2[::-1, ::-1]

array([[0, 0, 4, 3],
       [5, 0, 0, 9],
       [1, 0, 1, 6]])